In [1]:
%load_ext autoreload

# Examen

## Determinante

In [9]:
%autoreload 2
from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)


def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante usando el método...
    [Descomposición LU, eliminación gaussiana, Gauss-Jordan, Gauss-Jacobi o Gauss-Seidel]

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A

    """
    import numpy as np

    A = np.array(A, dtype=float)
    L, U = descomposicion_LU(A)

    det = 1.0
    for i in range(U.shape[0]):
        det *= U[i, i]

    return det


# Ejercicio 1

In [10]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
calc_determinante(A1)

[07-17 13:06:13][INFO] 
[[-4.    2.   -4.   -4.    1.    2.    5.    3.    5.    1.  ]
 [ 0.    0.5   3.    2.    0.25 -1.5   4.25  0.75  2.25  5.25]
 [ 0.    7.5  -9.    0.   -2.75  4.5   8.25  5.75 10.25  5.25]
 [ 0.    2.5   5.    0.   -4.25 -0.5   3.75 -0.75 -1.25  4.75]
 [ 0.    3.    0.   -2.    1.    2.    8.    2.    5.    3.  ]
 [ 0.   -1.   -1.   -3.   -1.5  -2.    4.5  -0.5   6.5  -0.5 ]
 [ 0.   -0.5  -6.   -5.   -0.25 -1.5   8.75  1.25  8.75  0.75]
 [ 0.    5.5  -6.    0.   -1.25  3.5  -0.25 -1.75  4.75  5.75]
 [ 0.   -2.    7.    7.   -4.   -4.   -7.   -3.    0.   -5.  ]
 [ 0.    3.    6.    0.   -1.5   0.    2.5  -2.5   0.5  -3.5 ]]
[07-17 13:06:13][INFO] 
[[ -4.     2.    -4.    -4.     1.     2.     5.     3.     5.     1.  ]
 [  0.     0.5    3.     2.     0.25  -1.5    4.25   0.75   2.25   5.25]
 [  0.     0.   -54.   -30.    -6.5   27.   -55.5   -5.5  -23.5  -73.5 ]
 [  0.     0.   -10.   -10.    -5.5    7.   -17.5   -4.5  -12.5  -21.5 ]
 [  0.     0.   -18.   -14.  

np.float64(9912776.000000015)

# Ejercicio 2

In [11]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
calc_determinante(A2)

[07-17 13:10:05][INFO] 
[[  2.    2.    4.    5.   -2.   -3.    2.   -2. ]
 [  0.    0.    5.    4.5   0.   -0.5  -3.    3. ]
 [  0.    3.   -7.   -8.    0.    5.    3.    5. ]
 [  0.   -2.    4.    6.   -3.    2.   -2.   -3. ]
 [  0.   -3.   -3.    2.5   6.    3.5   0.   -1. ]
 [  0.   -1.  -10.   -9.5   9.    6.5  -8.    3. ]
 [  0.   -8.   -7.   -8.    7.    9.   -5.    7. ]
 [  0.    3.    1.    5.    3.    1.    6.   -6. ]]


ValueError: No existe solución única.